-- Run this script in Supabase SQL Editor before starting the JavaFX app.
-- The Java application reads and writes to this public.expenses table through JDBC.

create table if not exists public.expenses (
    id bigint generated by default as identity primary key,
    item_name text not null,
    category text not null,
    currency text not null,
    amount numeric(12, 2) not null check (amount > 0),
    converted_php_value numeric(12, 2) not null check (converted_php_value >= 0),
    date_added date not null default current_date,
    created_at timestamp with time zone not null default now()
);

create index if not exists idx_expenses_category on public.expenses (category);
create index if not exists idx_expenses_date_added on public.expenses (date_added desc);

-- Sample queries for testing in Supabase SQL Editor:

select * from public.expenses order by date_added desc, id desc;

select category, sum(converted_php_value) as total_php
from public.expenses
group by category
order by total_php desc;

select sum(converted_php_value) as grand_total_php
from public.expenses;
